### ISSUE TITLE
Where is the original source code?

### ISSUE THREAD

**Issue by FilmCoder** [DavidKinder/Windows-Inform7#20]
@DavidKinder What happened to the original inform7 source code?

According to this talk:
http://inform7.com/talks/2019/06/14/narrascope.html

The original source code should be here, but the link is dead:
https://github.com/ganelson/inform

Does this repo contain all the source?  Is ganelson still around?  Is Inform7 still maintained?

Thank you!

PS.  I'm interested in using Inform7 as an engine to power a discord bot.

**Comment by DavidKinder** [comment]
Graham has not yet completed the overhaul of the Inform 7 codebase described in that talk (and the Narrascope 2020 talk). It is my understanding that those repositories will be made public when he considers it ready for a public release. Until then they remain private. Inform 7 is still maintained.

**Comment by FilmCoder** [comment]
@DavidKinder ahh OK.  So it's my understanding then, that this repo is a GUI editor for making Inform7 stories, and then you just pass the story to the Inform7 compiled binaries for processing into a final executable?  But you don't have access to the actual source code?

**Comment by DavidKinder** [comment]
The intention of the Inform 7 project was always that the front-ends (this project is the Windows front-end) and the underlying compiler formed a whole, but yes, this project is the source for the Windows GUI front-end. The source for the actual Inform 7 compiler has never been made public, as yet.
