### ISSUE TITLE
The IDE lacks options for creating and opening project-specific/local extensions

### ISSUE THREAD

**Issue by navaronbracke** [DavidKinder/Windows-Inform7#31]
When globally importing an Inform 7 extension in the IDE, it becomes available for use in the `Extensions` panel.
(the extension gets copied into the Inform/Extensions/<author> folder)
This allows a user to open the extension inside the IDE itself.

However, there are no options for creating and opening a _project specific_ extension.
The documentation states that these end up in the project's materials folder like so:
```
MyProject/
- MyProject.inform/
- MyProject.materials/
   - Release/ 
   - Extensions/
     -  Author/
        -  MyExtension.i7x
```
Such extensions can be successfully imported into the project.
The IDE just lacks menu options for creating them and opening them.
They are also not listed under `Extensions`.

It would be nice if we could:
1) Create an extension for the current project only.
Instead of creating the Author folder in the global Inform directory, just create it under the projects materials directory, as shown above.
2) Open an extension that is located inside the project's materials directory.
3) See the locally installed extension under the `Extensions` panel. (perhaps marked with `local extension`)

**Comment by DavidKinder** [comment]
This is an issue with all the front-ends, but just the Windows front-end.

To do this properly will require co-operation between the ni compiler and the front-ends. This is not likely to get addressed until the open source release of Inform 7.

**Comment by navaronbracke** [comment]
This being an issue on all the front-ends seems logical, as they all use the same underlying system. On the other hand, it is great to hear that Inform 7 is finally getting an open source release.

**Comment by glindsey** [comment]
Not to necro this issue, but could you clarify why this needs cooperation between the compiler and front-ends? If there's a bug in one of my project-specific extensions, and I click the arrow icon in the error message, the IDE opens the extension file in a window. Couldn't there also be an option in the File menu to just open any old "i7x" file in the same manner? I guess I'm describing a separate issue from actually creating/opening a local extension as a project, though.

**Comment by DavidKinder** [comment]
> could you clarify why this needs cooperation between the compiler and front-ends?

A fair question. The original poster listed three issues. Of these, only the third definitely needs the compiler to be involved, since the HTML displayed in the Extensions tab is generated by the ni compiler. The first two could in principle be done just in the front-end. However I'd prefer to do that in concert with the other front-ends, and at the moment, with Graham tied up with his rewrite work, I think that that is best left until Graham has made the next release available.
