### ISSUE TITLE
The build does not produce a working application

### ISSUE THREAD

**Issue by AlexProudfoot** [DavidKinder/Windows-Inform7#55]
Attempting to compile produces error 512.

![Untitled](https://user-images.githubusercontent.com/49520257/181227099-2c9fde2e-6970-41b5-b30f-2d081f9efbb0.png)

Should the command line be invoking **ni.exe** rather than **inform7.exe** which doesn't exist in the compilers directory?

*Update - Copying ni.exe to inform7.exe doesn't help since the error "VM not set" is revealed.*

**Comment by DavidKinder** [comment]
The latest front-end code will only work with the soon-to-be-released version of Inform 7 from https://github.com/ganelson/inform. You'll need to either build that yourself, or build the front end from one of the tagged releases, or tweak the logic in ProjectFrame.cpp to use the right command line format for 6M62 (the code is in there but set up for the next build).

**Comment by AlexProudfoot** [comment]
Thanks David.

**Comment by AlexProudfoot** [comment]
The command line tools build and run under Cygwin but merely copying the inform folder into the distribution folder (which seems to be the logical next step) doesn't produce a working build. The compiler and it's support files don't end up in the compilers folder as I assume is intended.

**Comment by DavidKinder** [comment]
The correct incantation to copy everything into the build directory is (from "Distribution/inform") "make forceintegration".

**Comment by AlexProudfoot** [comment]
Thanks David, that seems to have worked. By the way, the hunspell source code is now in src/hunspell.

**Comment by AlexProudfoot** [comment]
Here is the result of compiling Onyx.

![Untitled](https://user-images.githubusercontent.com/49520257/181905348-f0312b13-b610-42cd-8176-59eb7fd9e0ef.png)

Here are the current library versions.

![Untitled](https://user-images.githubusercontent.com/49520257/181905446-929eb72e-c7b9-4e98-957d-28c49d1723b5.png)

**Comment by AlexProudfoot** [comment]
Oh, I just noticed that the automatic indentation in the source pane isn't working.
