### ISSUE TITLE
Automatic indentation is not working

### ISSUE THREAD

**Issue by AlexProudfoot** [DavidKinder/Windows-Inform7#56]
The room description text should be indented on wrap around.

![Untitled](https://user-images.githubusercontent.com/49520257/182358986-12a0a214-979e-41f2-a438-456c32a972a2.png)

**Comment by DavidKinder** [comment]
The "Indent wrapped lines" option was removed by commit d894fdb0659a88fb6c7dbefc179652c44181b60b, following its removal from the MacOS front-end - Graham and Toby decided that they didn't like that option, so it is gone.
