### ISSUE TITLE
The "Open a Sample Project" links don't work

### ISSUE THREAD

**Issue by AlexProudfoot** [DavidKinder/Windows-Inform7#59]
The "Open a Sample Project" links produce a "Create Project" dialog instead of opening the installed samples.

**Comment by DavidKinder** [comment]
I don't see this. Is this a build you've made yourself, or the official release?

**Comment by AlexProudfoot** [comment]
The official release.

**Comment by DavidKinder** [comment]
What should happen (and what I get) is that you get a save dialog to say where the sample project should be copied to, and after choosing a location, the sample project opens in Inform.

**Comment by AlexProudfoot** [comment]
OK. It works as you described in both the official release and the compiled from source versions. It was just a bit counterintuitive to see a create project dialog in response to "Open a Sample Project". Maybe the installer/app could copy the samples to the working directory structure on installation/first use? Just a suggestion.

**Comment by DavidKinder** [comment]
I have re-worded the text on that save dialog to hopefully make things clearer. I'm reluctant to change the behaviour beyond that as this is how the macOS front-end works, which I tend to try to follow with the Windows front-end, where practical.
