### ISSUE TITLE
Display an explicit error if i6, ni, or the interpreter is missing from the I7 package

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Windows-Inform7#69]
This is stupid, but we keep getting reports where Norton swipes part of the toolchain and carries it off to its lair deep in the maze. To users, this looks like "the game just silently doesn't work" or "the Story pane is blank".

The IDE should detect this case and say "Check your antivirus".

**Comment by DavidKinder** [comment]
This has already been done, at least for missing interpreters, in commit 0b5f6c631baeda9e9df9429f6812a285b0b5d639. Doing the same for the compilers is a good idea.

**Comment by erkyrath** [comment]
Whoops! Should have checked the commit history before I posted. Anyway, good, thanks.

**Comment by DavidKinder** [comment]
This should also cover inbuild too, now.

**Comment by DavidKinder** [comment]
Commit bcee6df2a07892da5a081c292d169de20e240d3a adds a check of all secondary executables when starting the front-end. If any are missing the user is warned, along with a suggestion that anti-virus might have quarantined something it should not have.
