### ISSUE TITLE
Build Problem related to Dark Mode

### ISSUE THREAD

**Issue by AlexProudfoot** [DavidKinder/Windows-Inform7#71]
![Untitled](https://github.com/DavidKinder/Windows-Inform7/assets/49520257/ccfd41db-417d-4ba7-bf6a-c9adb563c0b6)

**Comment by AlexProudfoot** [comment]
![Untitled](https://github.com/DavidKinder/Windows-Inform7/assets/49520257/c48e2726-c4c6-4555-962f-5727acaff090)

**Comment by AlexProudfoot** [comment]
![Untitled](https://github.com/DavidKinder/Windows-Inform7/assets/49520257/30760b00-7bbc-4e2f-9484-78f44261a9e4)

**Comment by DavidKinder** [comment]
You need the Windows 11 SDK installed as part of the Visual C++ setup. I've updated the README.md file to mention this.
