### ISSUE TITLE
Release Website Wrongly Generated

### ISSUE THREAD

**Issue by AlexProudfoot** [DavidKinder/Windows-Inform7#72]
This applies to 10.1.2 and 10.2.0-beta+6W68.

![Untitled](https://github.com/DavidKinder/Windows-Inform7/assets/49520257/a01af2e2-5fe4-4209-adfa-f54c0bad0193)

**Comment by AlexProudfoot** [comment]
This is how 6M62 renders the website.

![Untitled](https://github.com/DavidKinder/Windows-Inform7/assets/49520257/23e93b71-8aef-432d-ba2b-64e9d10bc7eb)

**Comment by DavidKinder** [comment]
This looks to be an issue with the core Inform system, rather than the Windows front-end, so should be reported at https://inform7.atlassian.net/jira/software/c/projects/I7/issues
