### ISSUE TITLE
An option to also generate Project.intert when Release for Testing

### ISSUE THREAD

**Issue by kdabwl** [DavidKinder/Windows-Inform7#75]
Hello, I'm a seasoned (&retired) developer and try to study many Interpreter Compiletime and Runtime systems since the release of `Smalltalk-80 The Language and its Implementation`.
Would it be possible to support an ***option in Preferences***, to also generate `Project.intert` when ***Release for Testing***.
Also, the possibility for selecting which version (installed) of Inform utilities and compiler (maybe by pointing to directory) has to be used, in case for comparing Inform releases.
Thank you for consideration.

**Comment by DavidKinder** [comment]
It unlikely that we'll add an option to generate the intert file from the front-end: there are just so many options with the command-line Inform tools, and it was never the intention that the front-end would support anything other than a small subset of them. You can tell what command line the front-end has used from the Results tab (in the Console section) and then use that to guide you as to what you want for a command line, using the documentation at https://ganelson.github.io/inform/

On the Settings tab there is already a drop-down to specify the version of the compiler tools to use, of the ones included in the latest builds of Inform 7. An issue to add a way to specify the compiler tools by directory is here: https://github.com/DavidKinder/Windows-Inform7/issues/74
